### ISSUE TITLE
Jquery-ui folder isn't present in stylesheets folder

### ISSUE THREAD

**Issue by primatetv** [consuldemocracy/consuldemocracy#5305]
### User Story

I'm not that familiar with rails

### Why is this Needed?

To install consuldemocracy locally

### Description

im getting this error after following all the steps for installing consuldemocracy locally:
" ActionView::Template::Error (Error: File to import not found or unreadable: jquery-ui/themes/base/theme.
        on line 10:1 of app/assets/stylesheets/application.scss
>> @import "jquery-ui/themes/base/theme";

   ^
):"

Jquery-ui folder isn't present in stylesheets folder

**Comment by Senen** [comment]
Hi @primatetv,

Since PR #5159, we have been using Nodejs packages. You must install the Nodejs version defined in the `.node-version` file (currently 18.18.2) and then run the `bin/setup` command. The setup command runs `npm install`, which installs the Nodejs dependencies defined in the `package.json` file within the project `node_modules` folder.

Let me know if this solves your local installation problems.

I use [FNM](https://github.com/Schniz/fnm) to set up the Nodejs version defined for each project I work on. It sets up the proper Nodejs version, [parsing the .node-version file automatically](https://github.com/Schniz/fnm#bash). You can use the Nodejs version manager of your choice, though.

**Comment by javierm** [comment]
Closing since, as mentioned by @Senen, running `npm install` should solve the issue.

@primatetv Feel free to reopen if that isn't the case! :wink:
