### ISSUE TITLE
Installation consultation

### ISSUE THREAD

**Issue by NagusInfo** [consuldemocracy/consuldemocracy#5549]
I have installed the platform (thank you very much, it is wonderful) but I still can't figure out how to Support a Proposal. When I click on the Support button, I get a message that says "You do not have permission to perform the action "vote" on a Citizen's Proposal."
It is probably something in the user profile settings, or... I don't know. Could you help me? Thanks!!

**Comment by javierm** [comment]
Hi, @NagusInfo :smile:.

Are you using a browser with JavaScript enabled? In theory, what you mention only happens when JavaScript is disabled :thinking:. With JavaScript enabled, the "support" button should get replaced by a link to verify your account when you click on it.

In any case, only verified users can support proposals. That means that you either need to enable the "skip user verification" feature (in the admin section, Settings -> Global Settings -> Features) or configure an integration with a census so people can verify their account.

Let me know whether these suggestions solve the problem!

**Comment by NagusInfo** [comment]
Hola Javi, muchas gracias por tu respuesta.

Estamos utilizando el browser con JavaScript habilitado. Nuestro problema
principal es que los usuarios los estaremos creando desde el administrador.
Lo que nos sucede es que las propuestas no aparecen en los listados de
propuestas. Sí en los privados o cuando las ponemos en destacadas.
Utilizamos la opción de skip user verification. No queremos, en un
principio, votar las propuestas. Pero si ponemos votar, nos muestra un
cartel  indicando que no tenemos permiso (somos administradores): No tienes
permiso para realizar la acción 'vote' sobre Propuesta ciudadana.

Saludos,

*Sergio Marino*

**Comment by javierm** [comment]
Hi, @NagusInfo :smile:.

(The answer in Spanish is below the one in English).

Since the proposals don't appear on the list of proposals, and you can't support them, one possible cause could be that the proposals have been created but not published :thinking:. If you go to "my content", do the proposals you've created appear as "draft"?

If they're a draft, a possible explanation could be that, when you create a proposal, you get this:

> If you want recommendations to prepare the publishing leave your proposal as a draft and we will guide you.

And the options are "Yes, I want help and I'll publish later" or "No, I want to publish the proposal". So, you need to answer "No" to publish the proposal and "Yes" if you don't want to publish it :relieved:. Sorry for that! :pray:

En español:

Como las propuestas no aparecen en el listado, y no puedes apoyarlas, es posible que las propuestas se hayan creado pero no estén publicadas :thinking:. Si vas a "Mi contenido", ¿te aparecen en estado "borrador"?

Si son un borrador, una posible explicación podría ser que, cuando creas una propuesta, aparece:

> Si quieres recomendaciones para preparar la publicación deja tu propuesta como borrador y te guiaremos.

Y las opciones son "Si, quiero ayuda y publicaré mas tarde" o "No, quiero publicar la propuesta ya". Es decir, tienes que contestar "No" para publicar" y "Sí" en caso de no querer publicarla :relieved:. Disculpa que no sea nada claro :pray:.

**Comment by NagusInfo** [comment]
Gracias por la respuesta Javi,
Te escribí en castellano porque pensé que no sería un problema, si estoy
equivocado por favor avisame.

Hago un recorrido completo del problema y de cuál es nuestra intención
funcional, a ver si me puedo explicar.

Mi usuario figura como Admin y cuenta confirmada.
[image: image.png]
Creo una Propuesta para probar
[image: image.png]
La propuesta no se muestra en la sección. Entonces voy a Moderar Propuestas
[image: image.png]
En pendientes de revisión tampoco aparece, pero sí en Todas
[image: image.png]
Hago clic en Moderar y al botón de Marcar como revisadas. Aparece el cartel
de advertencia
[image: image.png]
Doy Aceptar, pero no se modifica el estado.

Revisemos la configuración.
En Menú/Administración/Propuesta figura seleccionada
[image: image.png]
En Configuración/Configuración Global/Funcionalidades figura así
[image: image.png]
Entonces en la sección de Propuestas se ve así
[image: image.png]
Al hacer clic en Apoyar me sale este aviso
[image: image.png]
Por lo que vuelvo a Configuración/Configuración Global/Funcionalidades y lo
cambio
[image: image.png]
Vuelvo a la sección de Propuestas y ahora me muestra
[image: image.png]
Mi preferencia es que NO se requiera verificación, pero de todas formas al
tratar de verificar me muestra
[image: image.png]
Y los Códigos Postales no los tengo configurados, por lo que no me deja
verificar... y hasta acá llegué.


Nosotros pretendemos un funcionamiento mucho más simplificado.
Que todos los usuarios puedan publicar Propuestas (con aprobación de
moderación), que no sea necesario apoyarlas y que todos puedan comentarlas.
O sea, el sistema es muy completo y al tratar de recortar funcionalidades
no logro que funciones :-)


MIL GRACIAS!!

Saludos,

*Sergio Marino*

**Comment by NagusInfo** [comment]
Perdón, me olvidé de responder a tu pregunta puntual.
En Mi contenido me figura en Borrador
[image: image.png]
Cuando entro a la Propuesta no veo cómo sacarla de Borrador para que quede
publicada.
[image: image.png]
[image: image.png]

Saludos,

*Sergio Marino*

**Comment by javierm** [comment]
Hi, @NagusInfo :smile:.

I'm afraid I'm not seing the screenshots you're probably trying to attach :thinking:. Could you edit your comments on GitHub (and ping me when you've done so) in order to include the screenshots?

(En español): Me temo que no veo los pantallazos que creo que estás intentando adjuntar :thinking:. ¿Podrías editar tus comentarios en GitHub (y dame un toque cuando lo hagas :wink:) para incluir los pantallazos.

En cuanto al idioma, como hay más gente usando la aplicación que entiende inglés que la que entiende castellano, siempre contesto en inglés.

**Comment by javierm** [comment]
Hola, @NagusInfo :smile:.

Cuando tengas los pantallazos, me dices :wink:. A ver si hay suerte y resolvemos esto :relieved:.

**Comment by javierm** [comment]
Closing due to lack of response. @NagusInfo Feel free to reopen :wink:.
