### ISSUE TITLE
When the user is registered, it gets verified as a third level user immediately

### ISSUE THREAD

**Issue by oebelus** [consuldemocracy/consuldemocracy#5733]
## User Story

As an administrator, I want newly registered users to start unverified so that we can maintain control over the verification process and ensure user authenticity.

## Why is this Needed?

New users are automatically verified as a level three user, this bypasses our intended verification process and could potentially allow unauthorized access to features meant for verified users only (we want voting and other features to be created only by verified users)

## Description

*Type*: Bug

### Current Behavior

When a new user registers on the platform, they are immediately granted third-level verification status without going through any verification steps.

### Expected Behavior

New users should be registered with an unverified status. They should only gain verified status after going through the appropriate verification steps, which may include email confirmation, document verification, or admin approval.

### Steps to reproduce

1. Navigate to the user registration page
2. Fill out the registration form with valid information
3. Submit the form to create a new account
4. Confirm email
5. Log in with the newly created account
6. Check the user's verification status - it will show as fully verified (level 3)

**Comment by javierm** [comment]
Hi, @oebelus :smile:.

This is done by default because the verification process is different for every institution.

Make sure to disable the "Skip user verification" feature. You can do so in the admin area, under "Settings -> Global Settings -> Features".

After that, you'll have to [configure the census connection](https://docs.consuldemocracy.org/tech_docs/features/census_configuration) and/or [customize the code](https://docs.consuldemocracy.org/tech_docs/customization/introduction) to adapt it to your verification process.

Hope this helps!

**Comment by oebelus** [comment]
This was very helpful, thank you so much!
