### ISSUE TITLE
Installation of Wuerzburg repository

### ISSUE THREAD

**Issue by hermann-san** [consuldemocracy/consuldemocracy#5750]
Hi,
is it possible to install the [Wuerzburg repository](https://github.com/StadtWuerzburg) without the help of democracy today?
Has someone tried it and even run it successfully? Maybe with the OpenID / BundID Plugin?
Obviously, they would like to sell their services, so I don't expect any free help from them in this regard.

Thanks for sharing your thoughts and experiences.

PS. I would have asked this question in the forum, but it seems to be down for quite a while now.

**Comment by javierm** [comment]
Hi, @hermann-san :smile:.

I take it this is a technical question and not a legal one, right? :thinking: If it's a legal question, short answer: yes, since Consul Democracy and all its derivative works are licensed under the GNU Affero General Public License (AGPL).

If it's a technical question, we (Consul Democracy developers) are not familiar enough with their modifications, so we can't really help here :thinking:. You can try contacting the [Consul Democracy Foundation](https://consuldemocracy.org/); maybe they'll have more information!

**Comment by javierm** [comment]
Hope that helped!

**Comment by hermann-san** [comment]
@javierm   sorry for the late replay on this question and thanks for the answer.
I did check with  the company that makes that repository, but they were not ready to send me the source code of their product. I will check with the Consul democracy foundation now.

**Comment by hermann-san** [comment]
@javierm  the Consul democracy foundation has not responded to my question.

**Comment by javierm** [comment]
Hi, @hermann-san :smile:.

Recently the Foundation has added a new [Open source forks and modifications](https://docs.consuldemocracy.org/tech_docs/open_source/open-source-forks-and-modifications) page to the documentation. Does that help?

**Comment by javierm** [comment]
(I was answering that because of the "they were not ready to send me the source code of their product" part 🤔, but maybe I misunderstood what you meant 🤔.)
